[package]
name = "blood-bowl-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
convert_case = "0.8"
fluent-templates = "0.13"
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8", features = ["derive"] }